import AppLayout from '@/components/layouts/AppLayout';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'pepCode',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AppLayout>{children}</AppLayout>;
}
